[package]
name = "aarch64-air-lifter"
version = "0.1.0"
edition = "2021"

[dependencies]
target-lexicon = "0.12.16"
thiserror = "2.0.0"
tnj = { git = "ssh://git@github.com/TUM-DSE/tnj.git", rev = "c2d361a6e4c44143d35a863c8a0c1070b70223df" }
yaxpeax-arch = "0.3.2"
yaxpeax-arm = "0.3.0"
