[package]
name = "aarch64-air-lifter"
version = "0.1.0"
edition = "2021"

[dependencies]
filecheck = "0.5.0"
target-lexicon = "0.12.16"
thiserror = "2.0.0"
tnj = { git = "ssh://git@github.com/TUM-DSE/tnj.git", rev = "15833a816989b300f64ee6d0230679f98a22f26b" }
yaxpeax-arch = "0.3.2"
yaxpeax-arm = "0.3.0"
