name: Cargo check & test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/
            target/
          key: ${{ runner.os }}-cargo
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install additional dependencies
        run: |
          cargo install just cargo-sort cargo-nextest

      - name: Lint
        run: |
          just check
